dsadd ou   "OU=영업부,OU=서울본사,DC=studykorea,DC=kr"
dsadd ou   "OU=총무부,OU=서울본사,DC=studykorea,DC=kr"
dsadd ou   "OU=회계부,OU=서울본사,DC=studykorea,DC=kr"
dsadd ou   "OU=기술부,OU=서울본사,DC=studykorea,DC=kr"

dsadd user   "CN=박지완,OU=서울본사,DC=studykorea,DC=kr"   -samid   jwpark   -upn   jwpark@studykorea.kr   -fn   박지완   -pwd   p@ssw0rd1  -memberof  "CN=사장,OU=서울본사,DC=studykorea,DC=kr"
dsadd user   "CN=김가은,OU=기술부,OU=서울본사,DC=studykorea,DC=kr"   -samid   user11   -upn   user11@studykorea.kr   -fn   김가은   -pwd   p@ssw0rd1  -memberof  "CN=기술부사원,OU=서울본사,DC=studykorea,DC=kr" "CN=기술부부장,OU=서울본사,DC=studykorea,DC=kr" "CN=부장,OU=서울본사,DC=studykorea,DC=kr"
dsadd user   "CN=김승기,OU=기술부,OU=서울본사,DC=studykorea,DC=kr"   -samid   user12   -upn   user12@studykorea.kr   -fn   김승기   -pwd   p@ssw0rd1  -memberof  "CN=기술부사원,OU=서울본사,DC=studykorea,DC=kr"
dsadd user   "CN=문일영,OU=기술부,OU=서울본사,DC=studykorea,DC=kr"   -samid   user13   -upn   user13@studykorea.kr   -fn   문일영   -pwd   p@ssw0rd1  -memberof  "CN=기술부사원,OU=서울본사,DC=studykorea,DC=kr"
dsadd user   "CN=서민경,OU=기술부,OU=서울본사,DC=studykorea,DC=kr"   -samid   user14   -upn   user14@studykorea.kr   -fn   서민경   -pwd   p@ssw0rd1  -memberof  "CN=기술부사원,OU=서울본사,DC=studykorea,DC=kr"
dsadd user   "CN=송길호,OU=기술부,OU=서울본사,DC=studykorea,DC=kr"   -samid   user15   -upn   user15@studykorea.kr   -fn   송길호   -pwd   p@ssw0rd1  -memberof  "CN=기술부사원,OU=서울본사,DC=studykorea,DC=kr"
dsadd user   "CN=이헌종,OU=기술부,OU=서울본사,DC=studykorea,DC=kr"   -samid   user16   -upn   user16@studykorea.kr   -fn   이헌종   -pwd   p@ssw0rd1  -memberof  "CN=기술부사원,OU=서울본사,DC=studykorea,DC=kr"
dsadd user   "CN=정다연,OU=기술부,OU=서울본사,DC=studykorea,DC=kr"   -samid   user17   -upn   user17@studykorea.kr   -fn   정다연   -pwd   p@ssw0rd1  -memberof  "CN=기술부사원,OU=서울본사,DC=studykorea,DC=kr"
dsadd user   "CN=최창우,OU=기술부,OU=서울본사,DC=studykorea,DC=kr"   -samid   user18   -upn   user18@studykorea.kr   -fn   최창우   -pwd   p@ssw0rd1  -memberof  "CN=기술부사원,OU=서울본사,DC=studykorea,DC=kr"
dsadd user   "CN=강인석,OU=영업부,OU=서울본사,DC=studykorea,DC=kr"   -samid   user31   -upn   user31@studykorea.kr   -fn   강인석   -pwd   p@ssw0rd1  -memberof  "CN=영업부사원,OU=서울본사,DC=studykorea,DC=kr" "CN=영업부부장,OU=서울본사,DC=studykorea,DC=kr" "CN=부장,OU=서울본사,DC=studykorea,DC=kr"
dsadd user   "CN=김명선,OU=영업부,OU=서울본사,DC=studykorea,DC=kr"   -samid   user32   -upn   user32@studykorea.kr   -fn   김명선   -pwd   p@ssw0rd1  -memberof  "CN=영업부사원,OU=서울본사,DC=studykorea,DC=kr"
dsadd user   "CN=김지현,OU=영업부,OU=서울본사,DC=studykorea,DC=kr"   -samid   user33   -upn   user33@studykorea.kr   -fn   김지현   -pwd   p@ssw0rd1  -memberof  "CN=영업부사원,OU=서울본사,DC=studykorea,DC=kr"
dsadd user   "CN=안인호,OU=영업부,OU=서울본사,DC=studykorea,DC=kr"   -samid   user34   -upn   user34@studykorea.kr   -fn   안인호   -pwd   p@ssw0rd1  -memberof  "CN=영업부사원,OU=서울본사,DC=studykorea,DC=kr"
dsadd user   "CN=양보람,OU=영업부,OU=서울본사,DC=studykorea,DC=kr"   -samid   user35   -upn   user35@studykorea.kr   -fn   양보람   -pwd   p@ssw0rd1  -memberof  "CN=영업부사원,OU=서울본사,DC=studykorea,DC=kr"
dsadd user   "CN=윤한경,OU=영업부,OU=서울본사,DC=studykorea,DC=kr"   -samid   user36   -upn   user36@studykorea.kr   -fn   윤한경   -pwd   p@ssw0rd1  -memberof  "CN=영업부사원,OU=서울본사,DC=studykorea,DC=kr"
dsadd user   "CN=이빛나,OU=영업부,OU=서울본사,DC=studykorea,DC=kr"   -samid   user37   -upn   user37@studykorea.kr   -fn   이빛나   -pwd   p@ssw0rd1  -memberof  "CN=영업부사원,OU=서울본사,DC=studykorea,DC=kr"
dsadd user   "CN=최보성,OU=영업부,OU=서울본사,DC=studykorea,DC=kr"   -samid   user38   -upn   user38@studykorea.kr   -fn   최보성   -pwd   p@ssw0rd1  -memberof  "CN=영업부사원,OU=서울본사,DC=studykorea,DC=kr"
dsadd user   "CN=표세철,OU=영업부,OU=서울본사,DC=studykorea,DC=kr"   -samid   user39   -upn   user39@studykorea.kr   -fn   표세철   -pwd   p@ssw0rd1  -memberof  "CN=영업부사원,OU=서울본사,DC=studykorea,DC=kr"
dsadd user   "CN=박인호,OU=총무부,OU=서울본사,DC=studykorea,DC=kr"   -samid   user51   -upn   user51@studykorea.kr   -fn   박인호   -pwd   p@ssw0rd1  -memberof  "CN=총무부사원,OU=서울본사,DC=studykorea,DC=kr" "CN=총무부부장,OU=서울본사,DC=studykorea,DC=kr" "CN=부장,OU=서울본사,DC=studykorea,DC=kr"
dsadd user   "CN=방호연,OU=총무부,OU=서울본사,DC=studykorea,DC=kr"   -samid   user52   -upn   user52@studykorea.kr   -fn   방호연   -pwd   p@ssw0rd1  -memberof  "CN=총무부사원,OU=서울본사,DC=studykorea,DC=kr"
dsadd user   "CN=서인석,OU=총무부,OU=서울본사,DC=studykorea,DC=kr"   -samid   user53   -upn   user53@studykorea.kr   -fn   서인석   -pwd   p@ssw0rd1  -memberof  "CN=총무부사원,OU=서울본사,DC=studykorea,DC=kr"
dsadd user   "CN=양지영,OU=총무부,OU=서울본사,DC=studykorea,DC=kr"   -samid   user54   -upn   user54@studykorea.kr   -fn   양지영   -pwd   p@ssw0rd1  -memberof  "CN=총무부사원,OU=서울본사,DC=studykorea,DC=kr"
dsadd user   "CN=이한솔,OU=총무부,OU=서울본사,DC=studykorea,DC=kr"   -samid   user55   -upn   user55@studykorea.kr   -fn   이한솔   -pwd   p@ssw0rd1  -memberof  "CN=총무부사원,OU=서울본사,DC=studykorea,DC=kr"
dsadd user   "CN=임재진,OU=총무부,OU=서울본사,DC=studykorea,DC=kr"   -samid   user56   -upn   user56@studykorea.kr   -fn   임재진   -pwd   p@ssw0rd1  -memberof  "CN=총무부사원,OU=서울본사,DC=studykorea,DC=kr"
dsadd user   "CN=조상연,OU=총무부,OU=서울본사,DC=studykorea,DC=kr"   -samid   user57   -upn   user57@studykorea.kr   -fn   조상연   -pwd   p@ssw0rd1  -memberof  "CN=총무부사원,OU=서울본사,DC=studykorea,DC=kr"
dsadd user   "CN=김용현,OU=회계부,OU=서울본사,DC=studykorea,DC=kr"   -samid   user71   -upn   user71@studykorea.kr   -fn   김용현   -pwd   p@ssw0rd1  -memberof  "CN=회계부사원,OU=서울본사,DC=studykorea,DC=kr" "CN=회계부부장,OU=서울본사,DC=studykorea,DC=kr" "CN=부장,OU=서울본사,DC=studykorea,DC=kr"
dsadd user   "CN=이형규,OU=회계부,OU=서울본사,DC=studykorea,DC=kr"   -samid   user72   -upn   user72@studykorea.kr   -fn   이형규   -pwd   p@ssw0rd1  -memberof  "CN=회계부사원,OU=서울본사,DC=studykorea,DC=kr"
dsadd user   "CN=임세민,OU=회계부,OU=서울본사,DC=studykorea,DC=kr"   -samid   user73   -upn   user73@studykorea.kr   -fn   임세민   -pwd   p@ssw0rd1  -memberof  "CN=회계부사원,OU=서울본사,DC=studykorea,DC=kr"
dsadd user   "CN=정인혜,OU=회계부,OU=서울본사,DC=studykorea,DC=kr"   -samid   user74   -upn   user74@studykorea.kr   -fn   정인혜   -pwd   p@ssw0rd1  -memberof  "CN=회계부사원,OU=서울본사,DC=studykorea,DC=kr"
dsadd user   "CN=천호근,OU=회계부,OU=서울본사,DC=studykorea,DC=kr"   -samid   user75   -upn   user75@studykorea.kr   -fn   천호근   -pwd   p@ssw0rd1  -memberof  "CN=회계부사원,OU=서울본사,DC=studykorea,DC=kr"
dsadd user   "CN=최현정,OU=회계부,OU=서울본사,DC=studykorea,DC=kr"   -samid   user76   -upn   user76@studykorea.kr   -fn   최현정   -pwd   p@ssw0rd1  -memberof  "CN=회계부사원,OU=서울본사,DC=studykorea,DC=kr" 
dsadd user   "CN=한주영,OU=회계부,OU=서울본사,DC=studykorea,DC=kr"   -samid   user77   -upn   user77@studykorea.kr   -fn   한주영   -pwd   p@ssw0rd1  -memberof  "CN=회계부사원,OU=서울본사,DC=studykorea,DC=kr" 
dsadd user   "CN=홍성진,OU=회계부,OU=서울본사,DC=studykorea,DC=kr"   -samid   user78   -upn   user78@studykorea.kr   -fn   홍성진   -pwd   p@ssw0rd1  -memberof  "CN=회계부사원,OU=서울본사,DC=studykorea,DC=kr" 
