mkdir dockerfolder

root@docker-ubuntu:~/dockerfile# cat dockerfile 
FROM ubuntu:18.04
LABEL maintance="ychkim@lotte.net"
#install apache
RUN apt-get update \ 
    && apt-get install -y apache2
COPY index.html /var/www/html/index.html
EXPOSE 80
CMD ["/usr/sbin/apache2ctl","-D","FOREGROUND"]